version: "3.3"

services:
  database:
    image: postgres
    container_name: todo_app_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_app_database
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: todo_app_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
